language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=2.1.2
    - ALPINE_VER=3.8
  matrix:
    - NGINX_VER=1.15.8 TAGS=1.15,1,latest
    - NGINX_VER=1.14.2 TAGS=1.14
    - NGINX_VER=1.13.12 TAGS=1.13

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
      - $NOTIFICATIONS_EMAIL
    on_success: never
    on_failure: always
