language: bash

services:
  - docker

env:
  matrix:
    - NGINX_VER=1.15.6 TAGS=1.15,1,latest
    - NGINX_VER=1.14.1 TAGS=1.14
    - NGINX_VER=1.13.12 TAGS=1.13

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
      - $NOTIFICATIONS_EMAIL
    on_success: never
    on_failure: always
