name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.6.2
  ALPINE_VER: 3.8
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  nginx-119:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64','linux/arm64']
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.platform }}
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: 1.19.7
        tags: 1.19,1,latest
        platform: ${{ matrix.platform }}
  nginx-118:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64','linux/arm64']
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.platform }}
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: 1.18.0
        tags: 1.18
        platform: ${{ matrix.platform }}
  nginx-117:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.17.10
        tags: 1.17
  nginx-116:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.16.1
        tags: 1.16
  nginx-115:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.15.12
        tags: 1.15
  nginx-114:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.14.2
        tags: 1.14
  nginx-113:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.13.12
        tags: 1.13
